# These environment variables need to be defined for Travis:
#
# - SMTP_USERNAME
# - SMTP_PASSWORD
# - GITHUB_TOKEN (with 'repo' scope)

language: r
r:
- release
- oldrel
dist: bionic
sudo: false
cache: packages
warnings_are_errors: false
branches:
  only:
  - master
  - dev
latex: false
addons:
  apt:
    packages:
    - libmagick++-dev
    - libharfbuzz-dev
    - libfribidi-dev
r_packages:
- pkgdown
- hexSticker
- covr
- here
after_success:
- Rscript -e 'library(covr); codecov()'
notifications:
  email:
    recipients:
    - andrew@exegetic.biz
    on_success: change
    on_failure: change
before_deploy:
- Rscript inst/hex/emayili-hex.R
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  on:
    branch: master
  local_dir: docs
  target_branch: gh-pages
